# Generated by Django 2.0.2 on 2020-06-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=5, verbose_name='教师姓名')),
                ('tPhone', models.CharField(max_length=11, verbose_name='联系电话')),
            ],
        ),
    ]
